name: Update Branches
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:    
      - 'main'
      - 'release-v**'
    # paths-ignore:
    #   - 'docs/**'
    #   - '.github/'
    #   - 'CHANGELOG/'
    #   - 'charts/'
    #   - 'manifests/'
    #   - 'sample-docker-templates/'
  
jobs:
  change-target-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: Change Target Branch
      run: |
        # Set the new target branch name
        git fetch --all
        git checkout release-candidate
        git pull origin main
        git config --global user.email pawan.mehta@devtron.ai
        git config --global user.name pawan-mehta-dt
        git push origin release-candidate
