name: send-release-note

# Controls when the workflow will run
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  send_release_note:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        echo "PR ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }}) has been merged"
        echo ${{ github.event.pull_request.body }} > release-note.txt
        echo "## Release Note Goes below"
        cat release-note.txt
        sed ':a;N;$!ba;s/\n/\\n/g' -i release-note.txt
        echo "## Release note after substitution"
        content=$(cat release-note.txt)
        echo $content
        curl -H "Content-Type: application/json" -d "{\"username\": \"Release-note\", \"content\": \"${content}\"}" $DISCORD_WEBHOOK_URL
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        
